-- EventSearchFilterTest/LogSearchFilterTest(@DataJpaTest) 전용 최소 스키마.
--
-- securance-domain/src/test/resources/schema.sql의 tb_data_rcv_anal 정의와 동일한 이유로
-- (MariaDB VIRTUAL 생성 컬럼 등 H2로 그대로 이식하기 어려운 문법을 피해 엔티티가 매핑하는 컬럼만
-- 최소 재현) 이 모듈에도 같은 테이블을 둔다 — 두 모듈이 별도로 컴파일되는 test source set이라
-- 공유할 수 없다(운영 스키마 회귀 검증 목적이 아님에 주의).
CREATE TABLE tb_data_rcv_anal (
    anal_id                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    anal_date               VARCHAR(20) NOT NULL,
    anal_tp                 VARCHAR(5)  NOT NULL,
    anal_type               VARCHAR(5)  NOT NULL DEFAULT 'B',
    dtl_ip                  VARCHAR(20) NOT NULL,
    dtl_lane_no             TINYINT     NOT NULL,
    dtl_type                TINYINT     NOT NULL DEFAULT 1,
    dtl_no                  INT         NOT NULL DEFAULT 1,
    dtl_id                  BIGINT      NOT NULL DEFAULT 0,
    loc_id                  BIGINT NULL,
    grp_id                  BIGINT NULL,
    rcv_date                VARCHAR(20) NOT NULL,
    rcv_id                  BIGINT      NOT NULL DEFAULT 0,
    rcv_raw                 CLOB NULL,
    anal_header             VARCHAR(100) NULL,
    anal_data               CLOB NULL,
    anal_tail               VARCHAR(20) NULL,
    obj_cd                  VARCHAR(10) NOT NULL DEFAULT '',
    anal_data_stx           VARCHAR(10) NOT NULL DEFAULT '',
    anal_data_packet_len    VARCHAR(10) NOT NULL DEFAULT '',
    anal_data_protocol_ver  VARCHAR(10) NOT NULL DEFAULT '',
    anal_data_frame_option  VARCHAR(10) NOT NULL DEFAULT '',
    anal_data_address       VARCHAR(40) NOT NULL DEFAULT '',
    anal_data_command       VARCHAR(10) NOT NULL DEFAULT '',
    anal_data_subcommand    VARCHAR(10) NOT NULL DEFAULT '',
    anal_data_object_code   VARCHAR(10) NOT NULL DEFAULT '',
    anal_data_info_length   VARCHAR(10) NOT NULL DEFAULT '',
    anal_data_count         VARCHAR(10) NOT NULL DEFAULT '',
    anal_data_length        VARCHAR(10) NOT NULL DEFAULT '',
    anal_data_gate_name     VARCHAR(80) NOT NULL DEFAULT '',
    anal_data_ip            VARCHAR(20) NOT NULL DEFAULT '',
    anal_data_mac           VARCHAR(20) NOT NULL DEFAULT '',
    desc_data_info_length   VARCHAR(10) NOT NULL DEFAULT '',
    desc_gate_name          VARCHAR(80) NOT NULL DEFAULT '',
    desc_gate_ip            VARCHAR(20) NOT NULL DEFAULT '',
    desc_gate_lane_count    VARCHAR(20) NOT NULL DEFAULT '',
    desc_gate_lane_number   VARCHAR(20) NOT NULL DEFAULT '',
    desc_gate_type          VARCHAR(50) NOT NULL DEFAULT '',
    desc_user_mode          VARCHAR(30) NOT NULL DEFAULT '',
    desc_security_mode      VARCHAR(20) NOT NULL DEFAULT '',
    desc_inout_time         VARCHAR(20) NOT NULL DEFAULT '',
    desc_user_count         VARCHAR(20) NOT NULL DEFAULT '',
    desc_total_count        VARCHAR(20) NOT NULL DEFAULT '',
    desc_operation01        VARCHAR(20) NOT NULL DEFAULT '',
    desc_operation02        VARCHAR(20) NOT NULL DEFAULT '',
    desc_operation03        VARCHAR(20) NOT NULL DEFAULT '',
    desc_operation04        VARCHAR(20) NOT NULL DEFAULT '',
    desc_safety01           VARCHAR(20) NOT NULL DEFAULT '',
    desc_safety02           VARCHAR(20) NOT NULL DEFAULT '',
    desc_safety03           VARCHAR(20) NOT NULL DEFAULT '',
    desc_safety04           VARCHAR(20) NOT NULL DEFAULT '',
    desc_operation05        VARCHAR(20) NOT NULL DEFAULT '',
    desc_operation06        VARCHAR(20) NOT NULL DEFAULT '',
    desc_operation07        VARCHAR(20) NOT NULL DEFAULT '',
    desc_operation08        VARCHAR(20) NOT NULL DEFAULT '',
    desc_motor_count        INT         NOT NULL DEFAULT 0,
    desc_master_in_total    INT         NOT NULL DEFAULT 0,
    desc_gate_status01      VARCHAR(50) NOT NULL DEFAULT '',
    desc_gate_status02      VARCHAR(50) NOT NULL DEFAULT '',
    desc_gate_status03      VARCHAR(50) NOT NULL DEFAULT '',
    desc_gate_status04      VARCHAR(50) NOT NULL DEFAULT '',
    desc_gate_status05      VARCHAR(50) NOT NULL DEFAULT '',
    desc_gate_status06      VARCHAR(50) NOT NULL DEFAULT '',
    desc_gate_status07      VARCHAR(50) NOT NULL DEFAULT '',
    desc_gate_status08      VARCHAR(50) NOT NULL DEFAULT '',
    desc_gate_status09      VARCHAR(50) NOT NULL DEFAULT '',
    desc_gate_status10      VARCHAR(50) NOT NULL DEFAULT '',
    desc_gate_status11      VARCHAR(50) NOT NULL DEFAULT '',
    desc_gate_status12      VARCHAR(50) NOT NULL DEFAULT '',
    err_type                TINYINT     NOT NULL DEFAULT 0,
    resolve_yn              VARCHAR(1)  NOT NULL DEFAULT 'N',
    resolve_user            VARCHAR(50) NULL,
    resolve_date            TIMESTAMP NULL,
    has_status_event        BOOLEAN NOT NULL DEFAULT FALSE,
    has_error_event         BOOLEAN NOT NULL DEFAULT FALSE,
    reg_date                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
