-- V20 — tb_gate_log_event 제거 (2026-08-12)
--
-- V10에서 만든 tb_gate_log_event는 GATE_LOG(0x61) 패킷을 저장하는 두 파이프라인 중 하나였다
-- (GatePacketPersister.persistLogEntries → tb_gate_log_event). 그런데 실제 라우팅
-- 코드(DefaultGatePacketHandler.handle)를 확인한 결과, objectCode가 GATE_LOG일 때는 항상
-- GateLogService(tb_gate_log)로 직행하고 GatePacketPersister.persistReceivedPacket은 이
-- objectCode로는 아예 호출되지 않아, 이 테이블에 쓰는 코드 경로 자체가 도달 불가능했다.
--
-- 도달 불가능한 코드(GatePacketPersister의 GATE_LOG 분기, DataReceiveLog 엔티티/
-- DataReceiveLogRepository)를 제거하면서, 더 이상 어떤 코드도 쓰거나 읽지 않게 된 이 테이블도
-- 함께 정리한다. 개발 DB 확인 결과 0행이라 데이터 손실 없이 안전하게 제거할 수 있다
-- (docs/작업일지.md 0011 참고).
DROP TABLE IF EXISTS tb_gate_log_event;
