-- Codex 적대적 리뷰 재지적(2026-08-20, [P1]): V31의 applied_seq는 GateConnectionRegistryImpl이
-- 프로세스 로컬로 발급했다(벽시계 기반 + 인스턴스 판별자). 그런데 서로 다른 인스턴스가 같은
-- 밀리초에 같은 (dtl_ip, dtl_lane_no)의 상태를 갱신하면, 판별자는 값 충돌만 줄일 뿐 실제 이벤트
-- 발생 순서를 표현하지 못한다 — 나중에 발생한 이벤트가 더 작은 판별자를 뽑으면 seq가 더 작아져
-- upsertIfNewer의 `applied_seq <= VALUES(applied_seq)` 조건에 걸려 조용히 버려질 수 있다.
--
-- 이 시퀀스는 그 문제를 근본적으로 없앤다 — 인스턴스가 각자 발급하는 대신, DB가 발급하는 단일
-- 전역 카운터를 모든 인스턴스가 공유한다. `NEXT VALUE FOR` 한 문장이 원자적이므로(MariaDB
-- SEQUENCE 엔진이 내부적으로 직렬화) 두 인스턴스가 동시에 호출해도 같은 값이 나올 수 없고, 값의
-- 크기 순서가 곧 "DB가 그 요청을 처리한 순서"가 된다 — 벽시계 동기화(NTP) 여부와 무관하게 전역
-- 순서가 보장된다(GateConnectionRegistryImpl.enqueueNetStateUpdate 참고).
CREATE SEQUENCE IF NOT EXISTS tb_net_state_seq START WITH 1 INCREMENT BY 1;
